"""Postgres conversations baseline

The four tables of the conversation record, in the `conversations`
schema of the database the domain half also lives in: the session
spine, the turn timeline, the tool invocations a turn issued, and the
decision track underneath them.

Row ids are `bigint` identity columns, which is the load-bearing
difference from the SQLite-era baseline this replaces. That one asked
for `sqlite_autoincrement` because a plain `INTEGER PRIMARY KEY` reuses
the deleted maximum rowid, and retention deletes from exactly the end a
cursor points past. A Postgres sequence never hands out a value twice,
so the property the flag bought is now the column type's, and `bigint`
also makes the API's `MAX_ROW_ID` true by declaration.

`GENERATED BY DEFAULT` rather than `ALWAYS`, so a row may still be
inserted with an id named: a restore and the suites that plant rows
both do that, and `ALWAYS` would refuse them.

The revision id opens a new numbering block on purpose, for the reason
the domain baseline's does: no Postgres database can be stamped at the
old `0001`, because the only databases carrying it are SQLite files
this build cannot open.

The schema is not created here, for the reason the domain baseline
gives: `db.upgrade_to_head` creates it under the chain's advisory lock
before Alembic runs.

Autogenerated against `conversations.schema.metadata` through
`python -m vinga_server.db.migrations.autogen --conversations`, then
reviewed: the candidate is reproduced as it was written apart from the
revision identity, this docstring, and the formatting.

Revision ID: 1001_postgres_conversations
Revises:
Create Date: 2026-08-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1001_postgres_conversations"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The reconcile cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this event belongs to.",
        ),
        sa.Column(
            "t_ms",
            sa.Integer(),
            nullable=False,
            comment="The event's offset from session open, in milliseconds, aligned with the capture's decision track.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="The event name, from the event vocabulary the README's table defines.",
        ),
        sa.Column(
            "level",
            sa.Integer(),
            nullable=False,
            comment="The numeric logging level the event was emitted at.",
        ),
        sa.Column(
            "fields",
            sa.JSON(none_as_null=True),
            nullable=False,
            comment="The event's payload minus `event`, `session` and `device`, which live on this row and on the session. Field names are the event vocabulary's own, copied verbatim, which is the contract. Never content: the writer strips an utterance's or a reply's `text` and a tool call's `tool` name whatever the storage switches say, because content has its own tables and its own switch and this table is metadata-only by construction.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        schema="conversations",
    )
    op.create_index(
        "ix_events_session", "events", ["session", "id"], unique=False, schema="conversations"
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The session list's cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The session's uuid hex: the join key for every other table here, and the correlation key to the capture triplet of the same name.",
        ),
        sa.Column(
            "device",
            sa.Text(),
            nullable=True,
            comment="The device's MAC in canonical form. Null when the session was rejected before one was understood.",
        ),
        sa.Column(
            "client",
            sa.Text(),
            nullable=True,
            comment="The client identifier the device announced, when it announced one.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=True,
            comment="The agent the session opened with, before any handover.",
        ),
        sa.Column(
            "agents",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="Every agent the device is bound to, as the binding resolved at open.",
        ),
        sa.Column(
            "protocol",
            sa.Text(),
            nullable=True,
            comment="The device protocol version this session negotiated.",
        ),
        sa.Column(
            "started_at",
            sa.Text(),
            nullable=False,
            comment="When the session opened, UTC ISO-8601. Survives both storage switches: retention prunes on this column, and a record that cannot be pruned cannot be kept.",
        ),
        sa.Column(
            "closed_at",
            sa.Text(),
            nullable=True,
            comment="When the session closed, UTC ISO-8601. Null in a session that is still running, and in one whose close was never persisted, which a crash and a failed close transaction both leave behind.",
        ),
        sa.Column(
            "duration_s",
            sa.Float(),
            nullable=True,
            comment="How long the session lasted, in seconds. A measured number: null under metrics-off.",
        ),
        sa.Column(
            "close_reason",
            sa.Text(),
            nullable=True,
            comment="What ended the session, one of: limit, idle, drain, client, error. The first cause to fire wins. Null until the session closes.",
        ),
        sa.Column(
            "server_version",
            sa.Text(),
            nullable=True,
            comment="The server version that recorded this session.",
        ),
        sa.Column(
            "revision",
            sa.Text(),
            nullable=True,
            comment="The build revision that recorded this session.",
        ),
        sa.Column(
            "providers",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="The resolved provider entry per pipeline stage, the same structure the capture manifest carries. Holds environment variable names, never credentials.",
        ),
        sa.Column(
            "metrics",
            sa.Boolean(),
            nullable=False,
            comment="Whether metrics storage was on for this session, so a null number is distinguishable from a number that was never stored.",
        ),
        sa.Column(
            "text",
            sa.Boolean(),
            nullable=False,
            comment="Whether text storage was on for this session, so a null utterance is distinguishable from an utterance that was never stored.",
        ),
        sa.Column(
            "dropped",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Records this session lost: events refused at the in-flight bound, and anything a failed transaction rolled back. Written at close, so the store records its own incompleteness the way the capture manifest records `complete`. Zero under metrics-off.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("session", name=op.f("uq_sessions_session")),
        schema="conversations",
    )
    op.create_index(
        "ix_sessions_device", "sessions", ["device"], unique=False, schema="conversations"
    )
    op.create_index(
        "ix_sessions_started_at", "sessions", ["started_at"], unique=False, schema="conversations"
    )
    op.create_table(
        "tool_invocations",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False, comment="Row id."
        ),
        sa.Column(
            "turn",
            sa.BigInteger(),
            nullable=False,
            comment="The `turns.id` this call belongs to, resolved by the writer inserting the turn and its calls in one transaction.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this call belongs to, denormalized so retention and a session-scoped query need no join.",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Order within the round's call list, as the model issued it, handovers included.",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="Where the call was routed, one of: builtin, device, mcp, unknown.",
        ),
        sa.Column(
            "entry",
            sa.Text(),
            nullable=True,
            comment="The owning MCP entry's configured name for an `mcp` call, null otherwise. A name this deployment chose, so it survives text-off.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=True,
            comment="The called tool's name. Null under text-off: a tool's name originates off this server (a device's self-description, an MCP far side) exactly as its result does.",
        ),
        sa.Column(
            "malformed",
            sa.Boolean(),
            nullable=False,
            comment="Whether the model's arguments were not a JSON object.",
        ),
        sa.Column(
            "arguments",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="What the model passed. Null under text-off, and null when malformed.",
        ),
        sa.Column(
            "result",
            sa.Text(),
            nullable=True,
            comment="What the call answered, including a refusal. Null under text-off.",
        ),
        sa.Column(
            "is_error",
            sa.Boolean(),
            nullable=False,
            comment="Whether the call answered as an error.",
        ),
        sa.Column(
            "duration_ms",
            sa.Integer(),
            nullable=True,
            comment="How long the call took, in milliseconds. Null where nothing ran, as for a refused or a successful handover, and under metrics-off.",
        ),
        sa.CheckConstraint(
            "source in ('builtin', 'device', 'mcp', 'unknown')",
            name=op.f("ck_tool_invocations_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
        schema="conversations",
    )
    op.create_index(
        "ix_tool_invocations_session",
        "tool_invocations",
        ["session"],
        unique=False,
        schema="conversations",
    )
    op.create_index(
        "ix_tool_invocations_turn",
        "tool_invocations",
        ["turn"],
        unique=False,
        schema="conversations",
    )
    op.create_table(
        "turns",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The turn timeline's cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this turn belongs to.",
        ),
        sa.Column(
            "t_ms",
            sa.Integer(),
            nullable=False,
            comment="The utterance's offset from session open, in milliseconds, aligned with its `heard` event and with the capture's audio. Structural rather than telemetry: it survives both switches.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=True,
            comment="The agent that answered, which a handover makes different from the session's.",
        ),
        sa.Column(
            "heard",
            sa.Text(),
            nullable=True,
            comment="What the device's user said, as transcribed. Null under text-off.",
        ),
        sa.Column(
            "heard_duration_s",
            sa.Float(),
            nullable=True,
            comment="How long the utterance lasted, in seconds. Null under metrics-off.",
        ),
        sa.Column(
            "language",
            sa.Text(),
            nullable=True,
            comment="The language the transcript was recognized as. Neither a measured number nor conversation text, so it survives both switches.",
        ),
        sa.Column(
            "language_confidence",
            sa.Float(),
            nullable=True,
            comment="How sure the recognizer was of that language. Null under metrics-off.",
        ),
        sa.Column(
            "reply",
            sa.Text(),
            nullable=True,
            comment="What the assistant said, the legs joined. Null under text-off, and null when the reply spoke nothing.",
        ),
        sa.Column(
            "legs",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="One entry per agent that took part in this turn, `{agent, text, input_tokens, output_tokens}`, present only when a handover split the reply. The text half is null under text-off and the token halves under metrics-off, because a turn's totals blend agents that may use different models.",
        ),
        sa.Column(
            "asr_ms",
            sa.Integer(),
            nullable=True,
            comment="Transcription elapsed, in milliseconds. Null where no elapsed was measured this turn, and under metrics-off.",
        ),
        sa.Column(
            "first_token_ms",
            sa.Integer(),
            nullable=True,
            comment="Request to first token of the reply, in milliseconds. Null under metrics-off.",
        ),
        sa.Column(
            "llm_ms",
            sa.Integer(),
            nullable=True,
            comment="The reply's LLM round durations summed, in milliseconds. Null under metrics-off.",
        ),
        sa.Column(
            "tts_first_audio_ms",
            sa.Integer(),
            nullable=True,
            comment="The reply's first synthesis request to its first audio bytes, in milliseconds, measured at the provider boundary and deliberately not at the device. Null when the reply spoke nothing, and under metrics-off.",
        ),
        sa.Column(
            "rounds",
            sa.Integer(),
            nullable=True,
            comment="How many LLM rounds the reply took. Null under metrics-off.",
        ),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=True,
            comment="Input tokens summed across the turn's rounds; OTel's `gen_ai.usage.input_tokens`. Null when the provider reported no usage, and under metrics-off.",
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=True,
            comment="Output tokens summed across the turn's rounds; OTel's `gen_ai.usage.output_tokens`. Null when the provider reported no usage, and under metrics-off.",
        ),
        sa.Column(
            "tool_calls",
            sa.Integer(),
            nullable=False,
            comment="How many tool invocations this turn issued, which is how many `tool_invocations` rows point at it. Structural rather than telemetry: it survives both switches.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        schema="conversations",
    )
    op.create_index(
        "ix_turns_session", "turns", ["session", "id"], unique=False, schema="conversations"
    )


def downgrade() -> None:
    op.drop_index("ix_turns_session", table_name="turns", schema="conversations")
    op.drop_table("turns", schema="conversations")
    op.drop_index("ix_tool_invocations_turn", table_name="tool_invocations", schema="conversations")
    op.drop_index(
        "ix_tool_invocations_session", table_name="tool_invocations", schema="conversations"
    )
    op.drop_table("tool_invocations", schema="conversations")
    op.drop_index("ix_sessions_started_at", table_name="sessions", schema="conversations")
    op.drop_index("ix_sessions_device", table_name="sessions", schema="conversations")
    op.drop_table("sessions", schema="conversations")
    op.drop_index("ix_events_session", table_name="events", schema="conversations")
    op.drop_table("events", schema="conversations")
