"""Conversation threads baseline

The whole of the conversation record, re-cut. The four tables of the
session projection (the session spine, the turn timeline, the tool
invocations a turn issued, and the decision track underneath them) and
the two the thread is: `conversations`, the durable dialogue between a
user and exactly one agent, and `conversation_milestones`, the consent
recap checkpoints on one of those.

`conversation_milestones` is created here and written by nothing yet.
It ships with the baseline deliberately rather than as a migration of
its own later: the reset below is paid once, and a table whose shape is
already decided is cheaper as an empty table than as a second
compatibility event. The reference documents it as dormant, which is
what it is.

**This replaces `1001_postgres_conversations` rather than upgrading
it.** There is no migration and no backfill, which is the settled
decision (#190, amended 2026-08-21): `turns.conversation` is not null,
so every stored turn belongs to a thread, and a turn recorded before
threads existed could not. A database stamped `1001_postgres_conversations`
is therefore stranded, not upgradeable; it is refused loudly at boot
with the reset procedure rather than half-read, and the compatibility
decision is recorded as an addendum to
`docs/adr/2026-08-20-database-upgrades-have-a-compatibility-floor.md`.

The revision id opens no new numbering block, for the reason the id it
replaces did open one: nothing was ever stamped `1002`, and the
conversations chain is a single baseline whose whole history is this
file.

The five indexes the thread query paths need are created here rather
than left to a later change, so the baseline carries them from its
first run: the unique join key, the agent-filtered listing in its
keyset order, the unfiltered listing and retention's inactivity scan,
the per-thread turn walk, and the latest-milestone lookup.

The schema is not created here, for the reason the domain baseline
gives: `db.upgrade_to_head` creates it under the chain's advisory lock
before Alembic runs.

Autogenerated against `conversations.schema.metadata` through
`python -m vinga_server.db.migrations.autogen --conversations`, then
reviewed: the candidate is reproduced as it was written apart from the
revision identity, this docstring, and the formatting.

Revision ID: 1002_conversation_threads
Revises:
Create Date: 2026-08-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1002_conversation_threads"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "conversation_milestones",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Row id, and what a later milestone names as its `parent` when it consumed this one.",
        ),
        sa.Column(
            "conversation",
            sa.Text(),
            nullable=False,
            comment="The `conversations.conversation` this checkpoint is on.",
        ),
        sa.Column(
            "from_turn",
            sa.BigInteger(),
            nullable=False,
            comment="The `turns.id` of the first turn the summarizer actually read, and the first turn this checkpoint covers. Coverage is the inclusive range `from_turn` through `after_turn`, so that a recap bounded by its input budget cannot claim the turns it omitted: those are the ones below this id, truncated rather than summarized, and hydration treats them so.",
        ),
        sa.Column(
            "after_turn",
            sa.BigInteger(),
            nullable=False,
            comment="The `turns.id` of the last turn the summarizer read, and the last turn this checkpoint covers. Hydration reads this milestone plus the turns with a greater id, which is the whole of what the checkpoint replaces.",
        ),
        sa.Column(
            "parent",
            sa.BigInteger(),
            nullable=True,
            comment="The `conversation_milestones.id` whose text was part of this recap's input, and null when none was. The lineage is what makes erasure transitive: content that reached this row only through an earlier checkpoint is still this row's content.",
        ),
        sa.Column(
            "created_at",
            sa.Text(),
            nullable=False,
            comment="When the checkpoint was stored, UTC ISO-8601.",
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=True,
            comment="The recap, byte for byte as it was spoken. Conversation content under the uniform rule, so null under text-off, though the flow that writes one cannot run with text off.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_milestones")),
        schema="record",
    )
    op.create_index(
        "ix_conversation_milestones_conversation",
        "conversation_milestones",
        ["conversation", "id"],
        unique=False,
        schema="record",
    )
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The tie-break half of the thread listing's keyset cursor, since activity moves and two threads can share a timestamp.",
        ),
        sa.Column(
            "conversation",
            sa.Text(),
            nullable=False,
            comment="The thread's uuid hex: the join key `turns.conversation` and `conversation_milestones.conversation` carry, and what a resume addresses. Minted by the runtime at the activation that opens the thread, the same shape and role as `sessions.session`.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=False,
            comment="The agent this thread belongs to, and the only one it will ever have: a conversation is a dialogue with exactly one agent, so a handover starts a second thread rather than moving this one. Not null, unlike `sessions.agent` and `turns.agent`, because a thread with no agent is not a thread.",
        ),
        sa.Column(
            "device",
            sa.Text(),
            nullable=False,
            comment="The device the thread was begun on, in canonical MAC form. Provenance rather than ownership: a thread is agent-scoped, so a resume from any device bound to that agent reaches it, and this column says where it started rather than where it may be continued.",
        ),
        sa.Column(
            "title",
            sa.Text(),
            nullable=True,
            comment="What the thread is called, derived from the earliest utterance stored on it and truncated. The earliest utterance rather than the earliest turn, because a thread a session moved onto opens with the answer that greeted the move and nothing was heard on it. Conversation text, so it is null under text-off, and null in a thread that has never stored one.",
        ),
        sa.Column(
            "incomplete",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether a write this thread needed was lost, so a resume can say the record has gaps. Product state rather than telemetry, and therefore deliberately outside the metrics switch: `sessions.dropped` is zeroed under metrics-off and this is not. Written by the durable path, which arrives with the writer's acknowledgements; false in every thread until then.",
        ),
        sa.Column(
            "created_at",
            sa.Text(),
            nullable=False,
            comment="When the thread's first turn landed, UTC ISO-8601. The row materializes with that turn rather than at activation, so a wake that produced no transcript leaves no empty thread behind.",
        ),
        sa.Column(
            "last_active_at",
            sa.Text(),
            nullable=False,
            comment="When the thread's most recent turn landed, UTC ISO-8601, rewritten by every turn. The listing orders on it and retention prunes on it, which is what makes retention thread-aware: a thread stays whole while it is being talked to, however old the session that began it.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("conversation", name=op.f("uq_conversations_conversation")),
        schema="record",
    )
    op.create_index(
        "ix_conversations_agent_activity",
        "conversations",
        ["agent", "last_active_at", "id"],
        unique=False,
        schema="record",
    )
    op.create_index(
        "ix_conversations_last_active",
        "conversations",
        ["last_active_at", "id"],
        unique=False,
        schema="record",
    )
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The reconcile cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this event belongs to.",
        ),
        sa.Column(
            "t_ms",
            sa.Integer(),
            nullable=False,
            comment="The event's offset from session open, in milliseconds, aligned with the capture's decision track.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="The event name, from the event vocabulary the README's table defines.",
        ),
        sa.Column(
            "level",
            sa.Integer(),
            nullable=False,
            comment="The numeric logging level the event was emitted at.",
        ),
        sa.Column(
            "fields",
            sa.JSON(none_as_null=True),
            nullable=False,
            comment="The event's payload minus `event`, `session` and `device`, which live on this row and on the session. Field names are the event vocabulary's own, copied verbatim, which is the contract. Never content: the writer strips an utterance's or a reply's `text` and a tool call's `tool` name whatever the storage switches say, because content has its own tables and its own switch and this table is metadata-only by construction.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        schema="record",
    )
    op.create_index(
        "ix_events_session", "events", ["session", "id"], unique=False, schema="record"
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The session list's cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The session's uuid hex: the join key for every other table here, and the correlation key to the capture triplet of the same name.",
        ),
        sa.Column(
            "device",
            sa.Text(),
            nullable=True,
            comment="The device's MAC in canonical form. Null when the session was rejected before one was understood.",
        ),
        sa.Column(
            "client",
            sa.Text(),
            nullable=True,
            comment="The client identifier the device announced, when it announced one.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=True,
            comment="The agent the session opened with, before any handover.",
        ),
        sa.Column(
            "agents",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="Every agent the device is bound to, as the binding resolved at open.",
        ),
        sa.Column(
            "protocol",
            sa.Text(),
            nullable=True,
            comment="The device protocol version this session negotiated.",
        ),
        sa.Column(
            "started_at",
            sa.Text(),
            nullable=False,
            comment="When the session opened, UTC ISO-8601. Survives both storage switches: retention prunes on this column, and a record that cannot be pruned cannot be kept.",
        ),
        sa.Column(
            "closed_at",
            sa.Text(),
            nullable=True,
            comment="When the session closed, UTC ISO-8601. Null in a session that is still running, and in one whose close was never persisted, which a crash and a failed close transaction both leave behind.",
        ),
        sa.Column(
            "duration_s",
            sa.Float(),
            nullable=True,
            comment="How long the session lasted, in seconds. A measured number: null under metrics-off.",
        ),
        sa.Column(
            "close_reason",
            sa.Text(),
            nullable=True,
            comment="What ended the session, one of: limit, idle, drain, client, error. The first cause to fire wins. Null until the session closes.",
        ),
        sa.Column(
            "server_version",
            sa.Text(),
            nullable=True,
            comment="The server version that recorded this session.",
        ),
        sa.Column(
            "revision",
            sa.Text(),
            nullable=True,
            comment="The build revision that recorded this session.",
        ),
        sa.Column(
            "providers",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="The resolved provider entry per pipeline stage, the same structure the capture manifest carries. Holds environment variable names, never credentials.",
        ),
        sa.Column(
            "metrics",
            sa.Boolean(),
            nullable=False,
            comment="Whether metrics storage was on for this session, so a null number is distinguishable from a number that was never stored.",
        ),
        sa.Column(
            "text",
            sa.Boolean(),
            nullable=False,
            comment="Whether text storage was on for this session, so a null utterance is distinguishable from an utterance that was never stored.",
        ),
        sa.Column(
            "dropped",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Records this session lost: events refused at the in-flight bound, and anything a failed transaction rolled back. Written at close, so the store records its own incompleteness the way the capture manifest records `complete`. Zero under metrics-off.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("session", name=op.f("uq_sessions_session")),
        schema="record",
    )
    op.create_index(
        "ix_sessions_device", "sessions", ["device"], unique=False, schema="record"
    )
    op.create_index(
        "ix_sessions_started_at", "sessions", ["started_at"], unique=False, schema="record"
    )
    op.create_table(
        "tool_invocations",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False, comment="Row id."
        ),
        sa.Column(
            "turn",
            sa.BigInteger(),
            nullable=False,
            comment="The `turns.id` this call belongs to, resolved by the writer inserting the turn and its calls in one transaction.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this call belongs to, denormalized so retention and a session-scoped query need no join.",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Order within the round's call list, as the model issued it, handovers included.",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="Where the call was routed, one of: builtin, device, mcp, unknown.",
        ),
        sa.Column(
            "entry",
            sa.Text(),
            nullable=True,
            comment="The owning MCP entry's configured name for an `mcp` call, null otherwise. A name this deployment chose, so it survives text-off.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=True,
            comment="The called tool's name. Null under text-off: a tool's name originates off this server (a device's self-description, an MCP far side) exactly as its result does.",
        ),
        sa.Column(
            "malformed",
            sa.Boolean(),
            nullable=False,
            comment="Whether the model's arguments were not a JSON object.",
        ),
        sa.Column(
            "arguments",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="What the model passed. Null under text-off, and null when malformed.",
        ),
        sa.Column(
            "result",
            sa.Text(),
            nullable=True,
            comment="What the call answered, including a refusal. Null under text-off.",
        ),
        sa.Column(
            "is_error",
            sa.Boolean(),
            nullable=False,
            comment="Whether the call answered as an error.",
        ),
        sa.Column(
            "duration_ms",
            sa.Integer(),
            nullable=True,
            comment="How long the call took, in milliseconds. Null where nothing ran, as for a refused or a successful handover, and under metrics-off.",
        ),
        sa.CheckConstraint(
            "source in ('builtin', 'device', 'mcp', 'unknown')",
            name=op.f("ck_tool_invocations_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
        schema="record",
    )
    op.create_index(
        "ix_tool_invocations_session",
        "tool_invocations",
        ["session"],
        unique=False,
        schema="record",
    )
    op.create_index(
        "ix_tool_invocations_turn",
        "tool_invocations",
        ["turn"],
        unique=False,
        schema="record",
    )
    op.create_table(
        "turns",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic row id, never reused. The turn timeline's cursor.",
        ),
        sa.Column(
            "session",
            sa.Text(),
            nullable=False,
            comment="The `sessions.session` this turn belongs to.",
        ),
        sa.Column(
            "conversation",
            sa.Text(),
            nullable=False,
            comment="The `conversations.conversation` this turn belongs to, which with the column above is what makes the session view and the thread view two readings of one set of rows rather than two stores. Not null: every stored turn belongs to the thread that was active when it was spoken, the whole of the v1 rule, and a database this build wrote holds no turn from before threads existed.",
        ),
        sa.Column(
            "t_ms",
            sa.Integer(),
            nullable=False,
            comment="The utterance's offset from session open, in milliseconds, aligned with its `heard` event and with the capture's audio. Structural rather than telemetry: it survives both switches.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=True,
            comment="The agent that owns this turn, which is the one it started with and therefore the one whose thread the column above names. A handover makes it different from the session's, and makes it different from the agent that finished the reply; `legs` is where a split reply's per-agent truth lives.",
        ),
        sa.Column(
            "heard",
            sa.Text(),
            nullable=True,
            comment="What the device's user said, as transcribed. Null under text-off.",
        ),
        sa.Column(
            "heard_duration_s",
            sa.Float(),
            nullable=True,
            comment="How long the utterance lasted, in seconds. Null under metrics-off.",
        ),
        sa.Column(
            "language",
            sa.Text(),
            nullable=True,
            comment="The language the transcript was recognized as. Neither a measured number nor conversation text, so it survives both switches.",
        ),
        sa.Column(
            "language_confidence",
            sa.Float(),
            nullable=True,
            comment="How sure the recognizer was of that language. Null under metrics-off.",
        ),
        sa.Column(
            "reply",
            sa.Text(),
            nullable=True,
            comment="What the assistant said, the legs joined. Null under text-off, and null when the reply spoke nothing.",
        ),
        sa.Column(
            "legs",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="One entry per agent that took part in this turn, `{agent, text, input_tokens, output_tokens}`, present only when a handover split the reply. The text half is null under text-off and the token halves under metrics-off, because a turn's totals blend agents that may use different models.",
        ),
        sa.Column(
            "asr_ms",
            sa.Integer(),
            nullable=True,
            comment="Transcription elapsed, in milliseconds. Null where no elapsed was measured this turn, and under metrics-off.",
        ),
        sa.Column(
            "first_token_ms",
            sa.Integer(),
            nullable=True,
            comment="Request to first token of the reply, in milliseconds. Null under metrics-off.",
        ),
        sa.Column(
            "llm_ms",
            sa.Integer(),
            nullable=True,
            comment="The reply's LLM round durations summed, in milliseconds. Null under metrics-off.",
        ),
        sa.Column(
            "tts_first_audio_ms",
            sa.Integer(),
            nullable=True,
            comment="The reply's first synthesis request to its first audio bytes, in milliseconds, measured at the provider boundary and deliberately not at the device. Null when the reply spoke nothing, and under metrics-off.",
        ),
        sa.Column(
            "rounds",
            sa.Integer(),
            nullable=True,
            comment="How many LLM rounds the reply took. Null under metrics-off.",
        ),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=True,
            comment="Input tokens summed across the turn's rounds; OTel's `gen_ai.usage.input_tokens`. Null when the provider reported no usage, and under metrics-off.",
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=True,
            comment="Output tokens summed across the turn's rounds; OTel's `gen_ai.usage.output_tokens`. Null when the provider reported no usage, and under metrics-off.",
        ),
        sa.Column(
            "tool_calls",
            sa.Integer(),
            nullable=False,
            comment="How many tool invocations this turn issued, which is how many `tool_invocations` rows point at it. Structural rather than telemetry: it survives both switches.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        schema="record",
    )
    op.create_index(
        "ix_turns_conversation",
        "turns",
        ["conversation", "id"],
        unique=False,
        schema="record",
    )
    op.create_index(
        "ix_turns_session", "turns", ["session", "id"], unique=False, schema="record"
    )


def downgrade() -> None:
    op.drop_index("ix_turns_session", table_name="turns", schema="record")
    op.drop_index("ix_turns_conversation", table_name="turns", schema="record")
    op.drop_table("turns", schema="record")
    op.drop_index("ix_tool_invocations_turn", table_name="tool_invocations", schema="record")
    op.drop_index(
        "ix_tool_invocations_session", table_name="tool_invocations", schema="record"
    )
    op.drop_table("tool_invocations", schema="record")
    op.drop_index("ix_sessions_started_at", table_name="sessions", schema="record")
    op.drop_index("ix_sessions_device", table_name="sessions", schema="record")
    op.drop_table("sessions", schema="record")
    op.drop_index("ix_events_session", table_name="events", schema="record")
    op.drop_table("events", schema="record")
    op.drop_index(
        "ix_conversations_last_active", table_name="conversations", schema="record"
    )
    op.drop_index(
        "ix_conversations_agent_activity", table_name="conversations", schema="record"
    )
    op.drop_table("conversations", schema="record")
    op.drop_index(
        "ix_conversation_milestones_conversation",
        table_name="conversation_milestones",
        schema="record",
    )
    op.drop_table("conversation_milestones", schema="record")
