"""A thread's agent keeps its thread and may change its name

One column comment and nothing else. `conversations.agent` has said
since the baseline that the agent named there is "the only one it will
ever have", which conflated two facts that #356 pulls apart: a thread
really does belong to exactly one agent, and a handover really does
start a second thread rather than moving this one, but the NAME that
agent is filed under is not fixed. A rename rewrites this column in the
transaction that renames the agent, which is what keeps a renamed agent
able to resume its own history, while the dated columns beside it keep
the name of the moment they record.

A migration whose whole content is a comment is priced the way its
sibling on the memory chain is: the comment is committed DDL, so a
database migrated by an earlier build keeps saying something false until
something changes it there, and the baseline-equality test compares
column comments through Alembic's own autogeneration, so the declaration
and the migration move together or that test fails. It is forward-only
and it moves no row.

`docs/reference/conversations-schema.md` is rendered from these comments
and regenerates with it.

Written by hand rather than autogenerated, for the reason the memory
chain's forward comment migration gives: what autogenerate would emit
for this is exactly the operation below.

The revision id is shorter than the sentence it is short for, and it has
to be: Alembic's `alembic_version.version_num` is `varchar(32)`, so an
id longer than that migrates cleanly and then fails on the stamp, which
is the last statement of the upgrade. What this migration moves is a
thread's ownership, and it says so here rather than in an id nothing can
hold.

Revision ID: 1003_rename_moves_ownership
Revises: 1002_conversation_threads
Create Date: 2026-09-06
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1003_rename_moves_ownership"
down_revision: str | None = "1002_conversation_threads"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# What the column says now, and what it said before. Both spelled out
# here rather than imported from `conversations.schema`: a migration is
# a record of what happened, and one reading its comment out of the
# current declaration would rewrite its own history every time that
# declaration moved.
NOW = (
    "The agent this thread belongs to, and the only agent it will ever "
    "belong to: a conversation is a dialogue with exactly one agent, so "
    "a handover starts a second thread rather than moving this one. The "
    "name is the one that agent has now rather than the one it had "
    "then, because renaming an agent rewrites this column and is what "
    "keeps the thread reachable; the dated columns beside it, "
    "`sessions.agent` and `turns.agent`, keep the name of the moment "
    "they record. Not null, unlike those two, because a thread with no "
    "agent is not a thread."
)

BEFORE = (
    "The agent this thread belongs to, and the only one it will ever "
    "have: a conversation is a dialogue with exactly one agent, so a "
    "handover starts a second thread rather than moving this one. Not "
    "null, unlike `sessions.agent` and `turns.agent`, because a thread "
    "with no agent is not a thread."
)


def upgrade() -> None:
    op.alter_column(
        "conversations",
        "agent",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=NOW,
        existing_comment=BEFORE,
        schema="record",
    )


def downgrade() -> None:
    op.alter_column(
        "conversations",
        "agent",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=BEFORE,
        existing_comment=NOW,
        schema="record",
    )
