"""Agent memory baseline

The whole of the memory chain: one table, `facts`, and the index its
ordered read and its prune walk share. What an agent was asked to
remember stops being a Markdown file under `memory.dir` and becomes a
row in a schema the server owns, migrated at every boot.

The revision id opens the unused `2xxx` numbering block, which no
database has ever been stamped at: the SQLite-era `2001_json_body_baseline`
that once used the name belonged to the domain chain and to a build
that cannot open a SQLite file at all. Nothing here answers a database
from before the cutover, because there is no memory database from
before it: this baseline is the first revision this chain has ever had,
and a deployment upgrading into it starts with an empty table.

It creates nothing an operator has to migrate into. The file-backed
store is retired by the cutover rather than imported, which
`CHANGELOG.md` announces: existing files under the old `memory.dir` are
not read, not imported and not deleted, and archiving them is the
operator's own deliberate act.

The schema is not created here, for the reason the two sibling
baselines give: with `version_table_schema` configured, Alembic creates
its schema-qualified version table before this function runs, so a
`CREATE SCHEMA` as the first statement would be too late.
`db.upgrade_to_head` creates it under the chain's advisory lock, before
Alembic is invoked at all, and a deployment whose server role may not
create one runs `deploy/postgres-init.sql` administratively first.

Autogenerated against `memory.schema.metadata` through
`python -m vinga_server.db.migrations.autogen --memory`, then reviewed:
the candidate is reproduced as it was written apart from the revision
identity, this docstring, and the formatting.

Revision ID: 2001_agent_memory
Revises:
Create Date: 2026-08-30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2001_agent_memory"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "facts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False, comment="Monotonic row id, never reused. Insertion order is reading order, and #83's stable identity and tombstones lean on ids that a delete cannot hand out again."),
        sa.Column("agent", sa.Text(), nullable=False, comment="The agent that remembered this, by the name the configuration gives it. Renaming an agent orphans its rows, exactly as it orphaned its file."),
        sa.Column("at", sa.Text(), nullable=False, comment="When the fact was remembered, UTC ISO-8601. Read by nothing in this issue: it is here because a row written without its moment cannot recover it later, an operator inspecting orphaned memory deserves to know when it accrued, and #83's tombstone lifetime question needs it."),
        sa.Column("fact", sa.Text(), nullable=False, comment="The fact as it was stored, normalized to one line."),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facts")),
        schema="memory",
    )
    op.create_index(
        "ix_facts_agent", "facts", ["agent", "id"], unique=False, schema="memory"
    )


def downgrade() -> None:
    op.drop_index("ix_facts_agent", table_name="facts", schema="memory")
    op.drop_table("facts", schema="memory")
