"""Memory scopes, the held area, and the conversation ledger

What #83 needs of the storage, as one forward migration on the chain
`2001_agent_memory` opened. `facts` stops being one agent's list and
becomes one owner's list within a scope: `agent` is renamed to `owner`
in place, `scope` arrives beside it, and the pair `forgotten_at` and
`forgotten_in` gives a forgotten fact somewhere to be held until the
thread that forgot it ends. `state` is new and is the conversation
ledger, keyed rather than ordered.

Nothing is lost and nothing is converted. The rename carries every row
across as it stands, and the backfill makes each of them what it always
was, an agent-scope fact: the column arrives with a server-side default
so an existing row is written without one being invented for it, and
the default is dropped again immediately, because every insert from
here on names its scope and a default would let one that forgot to
land as an agent fact.

The two check constraints are hand-written, unlike the rest of this
file: autogenerate compares tables, columns, types and indexes, and a
`CheckConstraint` is invisible to it. They state what the store relies
on. Scope is one of the two a fact may carry, conversation data living
in `state` alone; and the held pair is null together or set together,
because every path that addresses a held fact reads one of the two and
means the other.

The index is reshaped rather than kept, since the access path moved:
one owner's rows within one scope, in insertion order. The partial
index beside it is the lifecycle path, held rows addressed by the
thread that forgot them, and it is partial because the held area is a
small corner of a table that a restore, an erasure, a retention prune
and the sweep would otherwise scan whole under the writer's lock.

The rename makes this a stop-then-start upgrade, which `CHANGELOG.md`
and the README's upgrade section both state: an old image still serving
while this runs would fail its next memory statement, since the column
it names is gone. An expand-and-contract migration would buy rolling
upgrades, and no supported deployment shape has them, so the price is
declined deliberately rather than paid by accident.

Autogenerated against `memory.schema.metadata` through
`python -m vinga_server.db.migrations.autogen --memory`, then reviewed:
the column rename is written by hand, because autogenerate sees a drop
and an add and a database that took that pair would have lost every
row; the check constraints are added; and the operations are ordered so
the backfill runs before anything constrains it.

Revision ID: 2002_memory_scopes
Revises: 2001_agent_memory
Create Date: 2026-08-30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2002_memory_scopes"
down_revision: str | None = "2001_agent_memory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# What every row a `2001_agent_memory` database holds becomes. There was
# one scope before this migration and it had no name; this is the name
# it turns out to have had.
EXISTING = "agent"


def upgrade() -> None:
    op.alter_column(
        "facts",
        "agent",
        new_column_name="owner",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=(
            "Whose fact this is, read under `scope`: an agent's configured "
            "name, or a device's MAC in canonical form. Renaming an agent "
            "orphans its rows, exactly as it orphaned its file, and replacing "
            "a device orphans that device's notes."
        ),
        existing_comment=(
            "The agent that remembered this, by the name the configuration "
            "gives it. Renaming an agent orphans its rows, exactly as it "
            "orphaned its file."
        ),
        schema="memory",
    )
    op.add_column(
        "facts",
        sa.Column(
            "scope",
            sa.Text(),
            nullable=False,
            server_default=EXISTING,
            comment=(
                "Which memory this fact belongs to, one of: agent, device. It "
                "decides what `owner` names and which caps the row is pruned "
                "against."
            ),
        ),
        schema="memory",
    )
    # The default has done its work the moment the column exists, and
    # keeping it would let an insert that named no scope land as an agent
    # fact. The tables declare none, so this is also what keeps a
    # comparison against them empty.
    op.alter_column("facts", "scope", server_default=None, schema="memory")
    op.add_column(
        "facts",
        sa.Column(
            "forgotten_at",
            sa.Text(),
            nullable=True,
            comment=(
                "When the fact was forgotten, UTC ISO-8601, and null while it "
                "is active. A forgotten fact is held rather than erased, so "
                "the undo the softness exists for can reach it; permanent "
                "forgetting deletes the row instead and never lands here."
            ),
        ),
        schema="memory",
    )
    op.add_column(
        "facts",
        sa.Column(
            "forgotten_in",
            sa.Text(),
            nullable=True,
            comment=(
                "The `record.conversations.conversation` the fact was "
                "forgotten in, and null while it is active. A held fact shares "
                "that thread's lifecycle: the undo window is the thread's "
                "lifetime, and the thread's erasure, its retention prune and "
                "the sweep each take the rows naming it."
            ),
        ),
        schema="memory",
    )
    op.create_check_constraint(
        op.f("ck_facts_scope"),
        "facts",
        "scope in ('agent', 'device')",
        schema="memory",
    )
    op.create_check_constraint(
        op.f("ck_facts_forgotten"),
        "facts",
        "(forgotten_at is null) = (forgotten_in is null)",
        schema="memory",
    )
    op.alter_column(
        "facts",
        "id",
        existing_type=sa.BIGINT(),
        existing_nullable=False,
        existing_server_default=sa.Identity(always=False),
        comment=(
            "Monotonic row id, never reused. Insertion order is reading order, "
            "and the id a fact is addressed by (updated, forgotten, restored) "
            "is this one, so a delete must never hand it out again."
        ),
        existing_comment=(
            "Monotonic row id, never reused. Insertion order is reading order, "
            "and #83's stable identity and tombstones lean on ids that a delete "
            "cannot hand out again."
        ),
        schema="memory",
    )
    op.alter_column(
        "facts",
        "at",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=(
            "When the fact was last written, UTC ISO-8601, refreshed by a "
            "correction. A row written without its moment cannot recover it "
            "later, and an operator inspecting orphaned memory deserves to know "
            "when it accrued."
        ),
        existing_comment=(
            "When the fact was remembered, UTC ISO-8601. Read by nothing in this "
            "issue: it is here because a row written without its moment cannot "
            "recover it later, an operator inspecting orphaned memory deserves "
            "to know when it accrued, and #83's tombstone lifetime question "
            "needs it."
        ),
        schema="memory",
    )
    op.drop_index(op.f("ix_facts_agent"), table_name="facts", schema="memory")
    op.create_index(
        "ix_facts_scope", "facts", ["scope", "owner", "id"], unique=False, schema="memory"
    )
    op.create_index(
        "ix_facts_forgotten",
        "facts",
        ["forgotten_in", "id"],
        unique=False,
        schema="memory",
        postgresql_where=sa.text("forgotten_in IS NOT NULL"),
    )
    op.create_table(
        "state",
        sa.Column(
            "conversation",
            sa.Text(),
            nullable=False,
            comment=(
                "The `record.conversations.conversation` this ledger belongs to. "
                "State shares its thread's lifecycle whole: the thread's erasure "
                "and its retention prune take these rows with them, and a "
                "deployment that stores no conversation text starts every thread "
                "with an empty ledger."
            ),
        ),
        sa.Column(
            "key",
            sa.Text(),
            nullable=False,
            comment=(
                "What the entry is called, chosen by the model. The identity of "
                "the row, which is the whole of the ledger's semantics: a write "
                "is an upsert by key, so there is no id and no order to address."
            ),
        ),
        sa.Column(
            "value",
            sa.Text(),
            nullable=False,
            comment="What is currently true under that key, normalized to one line.",
        ),
        sa.Column(
            "updated_at",
            sa.Text(),
            nullable=False,
            comment=(
                "When the entry was last written, UTC ISO-8601. The sweep reads "
                "it: state can precede its thread's row, which materializes at "
                "the first turn, so an orphan is only taken once it is older than "
                "the grace period."
            ),
        ),
        sa.PrimaryKeyConstraint("conversation", "key", name=op.f("pk_state")),
        schema="memory",
    )


def downgrade() -> None:
    op.drop_table("state", schema="memory")
    op.drop_index(
        "ix_facts_forgotten",
        table_name="facts",
        schema="memory",
        postgresql_where=sa.text("forgotten_in IS NOT NULL"),
    )
    op.drop_index("ix_facts_scope", table_name="facts", schema="memory")
    op.create_index(
        op.f("ix_facts_agent"), "facts", ["owner", "id"], unique=False, schema="memory"
    )
    op.drop_constraint(op.f("ck_facts_forgotten"), "facts", schema="memory")
    op.drop_constraint(op.f("ck_facts_scope"), "facts", schema="memory")
    op.drop_column("facts", "forgotten_in", schema="memory")
    op.drop_column("facts", "forgotten_at", schema="memory")
    # The scope goes with the column that carried it, and so does every
    # device fact: there is no agent this schema could file one under.
    op.execute("delete from memory.facts where scope <> 'agent'")
    op.drop_column("facts", "scope", schema="memory")
    op.alter_column(
        "facts",
        "owner",
        new_column_name="agent",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=(
            "The agent that remembered this, by the name the configuration "
            "gives it. Renaming an agent orphans its rows, exactly as it "
            "orphaned its file."
        ),
        schema="memory",
    )
