"""A rename moves an agent's memory rather than orphaning it

One column comment and nothing else. `facts.owner` has said since
`2001_agent_memory` that renaming an agent orphans its rows, which was
true of every build until #356: the rename is now one transaction across
the three schemas, and an agent's facts move with it.

A migration whose whole content is a comment looks like churn, and it is
not. The comment is committed DDL, so a database migrated by an earlier
build keeps saying something false until something changes it there; and
`test_the_baseline_builds_exactly_what_the_tables_declare` compares the
built schema with the declared metadata through Alembic's own
autogeneration, which compares column comments, so editing `schema.py`
alone fails that test. It is forward-only, and it moves no row, so the
standing compatibility promise is untouched.

Written by hand rather than autogenerated. What autogenerate would emit
for this is exactly the operation below, and running it would have
rebuilt the whole comparison to take one line out of it.

Revision ID: 2003_rename_moves_memory
Revises: 2002_memory_scopes
Create Date: 2026-09-06
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2003_rename_moves_memory"
down_revision: str | None = "2002_memory_scopes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# What the column says now, and what it said before. Both spelled out
# here rather than imported from `memory.schema`, which is the rule
# every migration in this chain keeps: a migration is a record of what
# happened, and one reading its comment out of the current declaration
# would rewrite its own history every time that declaration moved.
NOW = (
    "Whose fact this is, read under `scope`: an agent's configured "
    "name, or a device's MAC in canonical form. A rename moves an "
    "agent's rows with it, in the transaction that renames the agent, "
    "so a renamed agent keeps what it remembered; replacing a device "
    "orphans that device's notes."
)

BEFORE = (
    "Whose fact this is, read under `scope`: an agent's configured "
    "name, or a device's MAC in canonical form. Renaming an agent "
    "orphans its rows, exactly as it orphaned its file, and "
    "replacing a device orphans that device's notes."
)


def upgrade() -> None:
    op.alter_column(
        "facts",
        "owner",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=NOW,
        existing_comment=BEFORE,
        schema="memory",
    )


def downgrade() -> None:
    op.alter_column(
        "facts",
        "owner",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=BEFORE,
        existing_comment=NOW,
        schema="memory",
    )
