"""The conversation store's documentation, rendered from the tables.

One source, two renderings: `comment=` on every column is written once
and read here as the markdown reference committed at
`docs/reference/conversations-schema.md` and as what `samtal-server
conversations schema` prints. The drift test fails on a column with no
comment, which is the same discipline `Field(description=...)` enforces
for the domain models next door.

Everything here is deterministic: no timestamps, no set iteration, and
the column order is the schema's own declaration order. CI regenerates
the committed copy and diffs it byte for byte, so anything that varied
between two runs would turn the lane red on an unrelated change.

Two things a column renderer cannot document, and the honest answer to
each. The event vocabulary that fills `events.name` and `events.fields`
is defined by the server README's event table, which this links rather
than restating: thirty rows copied here would drift, and the store adds
no drift of its own because it copies field names verbatim. And the
correspondence to OpenTelemetry's GenAI conventions is a mapping
between two vocabularies rather than a property of one column, so it is
written out below where an exporter author reads it once.

Read-only, and deliberately so: nothing here opens a database, reads a
configuration file or needs a key.
"""

import textwrap

from sqlalchemy import Table

from samtal_server.conversations.schema import TABLES

# Where the reference wraps its prose. The tables cannot wrap (a row is
# a line), so only paragraphs go through this.
PROSE_WIDTH = 78

# The event vocabulary's authority, relative to the committed reference.
EVENT_TABLE = "../../samtal-server/README.md#logging"

# What an exporter maps onto, per the observability ADR's adoption of
# the GenAI conventions "where one exists". Left-hand side is this
# project's field name, right-hand side is the OTel attribute; the third
# column says where the field is found.
GEN_AI: tuple[tuple[str, str, str], ...] = (
    ("input_tokens", "gen_ai.usage.input_tokens", "`turns`, `turns.legs`, the `llm_round` event"),
    (
        "output_tokens",
        "gen_ai.usage.output_tokens",
        "`turns`, `turns.legs`, the `llm_round` event",
    ),
    ("model", "gen_ai.request.model", "the `llm_round`, `llm_retry` and `provider_failed` events"),
    ("type", "gen_ai.provider.name", "the provider-bearing events, and `sessions.providers`"),
    ("host", "server.address", "the provider-bearing events"),
)


def reference() -> str:
    """The whole reference document, rendered from the metadata."""
    lines = [
        "# Conversation store schema reference",
        "",
        "Generated from the SQLAlchemy metadata by `samtal-server conversations",
        "schema`. Do not edit this file by hand: CI regenerates it and fails on any",
        "difference, so an edit here is reverted by the next run. The text of a",
        "column description lives on the table in",
        "`samtal-server/samtal_server/conversations/schema.py`.",
        "",
        *_paragraph(
            "The store is a SQLite database, `conversations.db`, beside the domain "
            "configuration in `server.database.dir`. It holds what was said and what "
            "it cost to say it: the session spine, the turn timeline, the tool "
            "invocations a turn issued, and the decision track underneath them. Audio "
            "never enters it. The per-frame endpointer track and the dropped-frame "
            "counts stay in the session capture, which is the recording; this is the "
            "queryable record."
        ),
        "",
        "## The compatibility promise",
        "",
        *_paragraph(
            "Table names, column names and event field names are a compatibility "
            "surface. They change only as breaking changes, announced in the "
            "changelog, the same promise the structured events carry. Columns are "
            "added additively and a row written before an addition reads it as null."
        ),
        "",
        "## What is stored, and what the two switches take away",
        "",
        *_paragraph(
            "Recording is off unless `server.conversations.enabled` says otherwise. "
            "Under it, two independent storage switches decide what a row keeps, and "
            "every combination is a supported configuration."
        ),
        "",
        "| Switch | On | Off |",
        "| --- | --- | --- |",
        "| `metrics` | every measured number, and one `events` row per structured "
        "event | the numeric columns are null and no `events` rows are written |",
        "| `text` | conversation text, and tool names, arguments and results | those "
        "columns are null; the rows still land |",
        "",
        *_paragraph(
            "Three kinds of column survive both switches, and each for a reason worth "
            "stating. The session spine (`sessions.session`, its device and its "
            "timestamps) survives because retention, purging and every read key on "
            "it, and a record that cannot be pruned cannot be kept. The structural "
            "halves of a turn (`t_ms`, `agent`, `language`, `tool_calls`) survive "
            "because they are neither a measured number nor conversation text. And "
            "`sessions.metrics` and `sessions.text` record which way the switches "
            "were set for that session, so a null column is distinguishable from a "
            "column that was never stored."
        ),
        "",
        *_paragraph(
            "The switches are deployment-wide. Until per-user controls exist, "
            "enabling text storage on a device a household shares stores what guests "
            "say to it, which is the same statement the capture documentation makes "
            "about audio. Attributing a session on a shared device to one member "
            "needs voiceprint identification, which does not exist here yet, so the "
            "deletion unit that is enforceable today is the session."
        ),
        "",
        "## Retention and deletion",
        "",
        *_paragraph(
            "`server.conversations.retention_days` defaults to 90. Whole sessions "
            "whose `started_at` is older than the window are deleted, row and "
            "children together, when the server starts and at each session close. "
            "`retention_days: 0` keeps everything and is a deliberate choice rather "
            "than a default: a store without a policy retains forever."
        ),
        "",
        *_paragraph(
            "Deletion on demand is `samtal-server conversations purge`, by "
            "`--session`, `--device` or `--before`, combining with AND. It works "
            "directly against the file with no server running, because deletion has "
            "to work exactly when the server is broken or gone. Purging a session "
            "that is still running ends its recording: the writer finds the row gone "
            "at its next turn and stops writing for that session. Capture files are a "
            "separate instrument and are never touched; the session id is the "
            "correlation key for whoever needs to remove the matching triplet."
        ),
        "",
        *_paragraph(
            "Deletion is physical, not query-level. The database is opened with "
            "`PRAGMA secure_delete=ON`, so a freed page is overwritten with zeros "
            "instead of lingering in the freelist, and both retention and purge "
            "finish with `PRAGMA wal_checkpoint(TRUNCATE)` so the deleted frames do "
            "not survive in the write-ahead log. Two limits are stated rather than "
            "implied. A checkpoint a reader is blocking does not fail the deletion: "
            "the rows are committed, the truncation is owed, and it is retried at "
            "the next quiet moment, which is the server's next write or the next "
            "purge. `samtal-server conversations purge` says so when it leaves one "
            "owed. And copies that have already left the file (backups, filesystem "
            "snapshots) are the operator's to manage."
        ),
        "",
        "## Reading it",
        "",
        *_paragraph(
            "There is no analysis command. The store is SQL, and the way to read it "
            "beside a running server is a WAL-safe copy rather than `cp`: a plain "
            "copy of a database in WAL mode without its `-wal` sidecar is a database "
            "missing its most recent commits."
        ),
        "",
        "```bash",
        "sqlite3 /var/lib/samtal/conversations.db \".backup '/tmp/conversations.db'\"",
        "sqlite3 /tmp/conversations.db 'select * from turns order by id desc limit 20'",
        "```",
        "",
        *_paragraph(
            "The ids on `sessions`, `turns` and `events` are monotonic and never "
            "reused (SQLite `AUTOINCREMENT`), which is what makes them usable as "
            "cursors: a client that has read up to id N may ask for what came after "
            "it and cannot be handed a different row under the same number, even "
            "after retention has deleted from the end."
        ),
        "",
        "## The event vocabulary",
        "",
        *_paragraph(
            f"`events.name` and `events.fields` carry the structured event surface, "
            f"whose definition is the [server README's event table]({EVENT_TABLE}): "
            f"which events exist, and which fields each one carries. It is not "
            f"restated here, because a second copy of thirty rows is a second copy to "
            f"drift. The store copies field names verbatim from the payload, minus "
            f"`event`, `session` and `device`, which live on the row and on the "
            f"session."
        ),
        "",
        *_paragraph(
            "One field never arrives: the writer strips `text` from the "
            "text-bearing events before the row lands. Conversation text has its own "
            "columns and its own switch, and the `events` table is metadata-only from "
            "its first row."
        ),
        "",
        "## The OpenTelemetry GenAI correspondence",
        "",
        *_paragraph(
            "Usage and provider identity use the GenAI semantic conventions adapted "
            "to this project's field style, so an exporter maps by reading one table "
            "rather than by guessing."
        ),
        "",
        "| This project | OpenTelemetry | Where |",
        "| --- | --- | --- |",
        *[f"| `{name}` | `{attribute}` | {where} |" for name, attribute, where in GEN_AI],
        "",
        *_paragraph(
            "`stage` and `provider` keep their own names deliberately. `provider` is "
            "the configured entry's name, a samtal concept with different semantics "
            "from OTel's vendor field, and the convention is adopted where one "
            "exists rather than imposed where one does not."
        ),
        "",
        *_paragraph(
            "A turn's `input_tokens` and `output_tokens` are totals across its "
            "rounds, and after a handover they blend agents that may run different "
            "models. `turns.legs` carries the per-leg counts, and the per-round, "
            "per-model truth is the `llm_round` events in the same database, one join "
            "away."
        ),
        "",
        "## Tables",
        "",
    ]

    for table in TABLES:
        lines += _table_section(table)

    return "\n".join(lines).rstrip("\n") + "\n"


def _table_section(table: Table) -> list[str]:
    lines = [
        f"### `{table.name}`",
        "",
        "| Column | Type | Null | Description |",
        "| --- | --- | --- | --- |",
    ]
    lines += [
        f"| `{column.name}` | `{column.type}` | {_null(column.nullable)} | "
        f"{_cell(column.comment)} |"
        for column in table.columns
    ]
    lines.append("")
    return lines


def _null(nullable: bool) -> str:
    return "yes" if nullable else "no"


def _cell(comment: str | None) -> str:
    """Text inside a table cell. A pipe ends a cell even inside a code
    span, so it is escaped; and an undescribed column is a defect this
    makes visible rather than an empty cell to skim past."""
    if not comment:
        return "**(undescribed)**"
    return " ".join(comment.split()).replace("|", "\\|")


def _paragraph(prose: str) -> list[str]:
    """One paragraph, wrapped. The committed reference is read as a file
    as often as it is rendered, and an unwrapped paragraph makes every
    edit to it a one-line diff of the whole thing.

    Never inside a word or across a hyphen, for the reason the domain
    reference gives: the default would break an identifier in half and a
    code span split over two lines renders with a space in it."""
    return textwrap.wrap(prose, width=PROSE_WIDTH, break_long_words=False, break_on_hyphens=False)


__all__ = ["GEN_AI", "reference"]
