"""Baseline domain schema: one JSON body per entity

The whole domain chain, replacing revisions 0001 to 0004. Each entity
table is now its key columns, a `body` holding the entity's pydantic
model dumped as JSON, and, where the kind can hold one, its `secrets`
column; `devices` and `domain_settings` are unchanged.

The revision id opens a new numbering block on purpose. No database
was ever stamped `2001_json_body_baseline`, so a database from the
0001 to 0004 chain cannot be mistaken for one at head: Alembic fails
to locate its stored revision, and `db.migration_failure` answers that
with the sentence that says to delete this file and re-seed. Reusing
`0001` would have made those databases silently current and then broken
at the first read of a column that is no longer there.

Those four ids are named in `db.DOMAIN_SUPERSEDED`, which is what keeps
the sentence to the databases it is true of: a revision this build
cannot find because it is from a LATER chain gets the ordinary
migration-failure sentence instead, since that database is current and
its operator has to roll forward rather than delete it.

Domain databases written before this revision are not upgradeable, by
the decision recorded in the addendum to
`docs/adr/2026-08-20-database-upgrades-have-a-compatibility-floor.md`.

Autogenerated against `db.schema.metadata` through
`python -m vinga_server.db.migrations.autogen`, then reviewed: the
candidate is reproduced as it was written apart from the revision
identity, this docstring, and the quoting.

Revision ID: 2001_json_body_baseline
Revises:
Create Date: 2026-08-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2001_json_body_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent_defaults",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        # The singleton, enforced by the schema rather than by a
        # convention in the repository. Re-keying this table for
        # per-family defaults later is what Alembic is here for.
        sa.CheckConstraint("id = 'singleton'", name=op.f("ck_agent_defaults_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_defaults")),
    )
    op.create_table(
        "agents",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_agents")),
    )
    op.create_table(
        "devices",
        sa.Column("mac", sa.Text(), nullable=False),
        sa.Column("agents", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("mac", name=op.f("pk_devices")),
    )
    op.create_table(
        "domain_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_domain_settings")),
    )
    op.create_table(
        "mcp_servers",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("secrets", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_mcp_servers")),
    )
    op.create_table(
        "prompt_fragments",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_prompt_fragments")),
    )
    op.create_table(
        "providers",
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("secrets", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("stage", "name", name=op.f("pk_providers")),
    )


def downgrade() -> None:
    op.drop_table("providers")
    op.drop_table("prompt_fragments")
    op.drop_table("mcp_servers")
    op.drop_table("domain_settings")
    op.drop_table("devices")
    op.drop_table("agents")
    op.drop_table("agent_defaults")
