"""Postgres domain baseline

The whole domain chain against Postgres, replacing the SQLite-era
baseline `2001_json_body_baseline`. Same seven tables and the same one
JSON body per entity; what is new is that they live in the `domain`
schema of a shared database rather than in a file of their own.

The revision id opens a new numbering block on purpose, and the reason
is different from the last one's. No database can be stamped at the old
id and met by this build at all: the only databases carrying it are
SQLite files, and this build cannot open a SQLite file. The block is
fresh so that the two eras are never confused in a changelog or a
version table read by hand, not to make an arm somewhere answer them.
Nothing here answers a database from before the cutover, because there
is no such Postgres database.

The schema is not created here. With `version_table_schema` configured,
Alembic creates its schema-qualified version table before this function
runs, so a `CREATE SCHEMA` as the first statement would be too late;
`db.upgrade_to_head` creates it under the chain's advisory lock, before
Alembic is invoked at all.

Domain databases written before this revision are not upgradeable, by
the decision recorded in the second addendum to
`docs/adr/2026-08-20-database-upgrades-have-a-compatibility-floor.md`.

Autogenerated against `db.schema.metadata` through
`python -m vinga_server.db.migrations.autogen`, then reviewed: the
candidate is reproduced as it was written apart from the revision
identity, this docstring, and the formatting.

Revision ID: 3001_postgres_domain
Revises:
Create Date: 2026-08-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3001_postgres_domain"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent_defaults",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.CheckConstraint("id = 'singleton'", name=op.f("ck_agent_defaults_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_defaults")),
        schema="domain",
    )
    op.create_table(
        "agents",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_agents")),
        schema="domain",
    )
    op.create_table(
        "devices",
        sa.Column("mac", sa.Text(), nullable=False),
        sa.Column("agents", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("mac", name=op.f("pk_devices")),
        schema="domain",
    )
    op.create_table(
        "domain_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_domain_settings")),
        schema="domain",
    )
    op.create_table(
        "mcp_servers",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("secrets", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_mcp_servers")),
        schema="domain",
    )
    op.create_table(
        "prompt_fragments",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_prompt_fragments")),
        schema="domain",
    )
    op.create_table(
        "providers",
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("secrets", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("stage", "name", name=op.f("pk_providers")),
        schema="domain",
    )


def downgrade() -> None:
    op.drop_table("providers", schema="domain")
    op.drop_table("prompt_fragments", schema="domain")
    op.drop_table("mcp_servers", schema="domain")
    op.drop_table("domain_settings", schema="domain")
    op.drop_table("devices", schema="domain")
    op.drop_table("agents", schema="domain")
    op.drop_table("agent_defaults", schema="domain")
