"""The conversation store's documentation, rendered from the tables.

One source, two renderings: `comment=` on every column is written once
and read here as the markdown reference committed at
`docs/reference/conversations-schema.md` and as what `vinga-server
conversations schema` prints. The drift test fails on a column with no
comment, which is the same discipline `Field(description=...)` enforces
for the domain models next door.

Everything here is deterministic: no timestamps, no set iteration, and
the column order is the schema's own declaration order. CI regenerates
the committed copy and diffs it byte for byte, so anything that varied
between two runs would turn the lane red on an unrelated change.

Two things a column renderer cannot document, and the honest answer to
each. The event vocabulary that fills `events.name` and `events.fields`
is defined by the event registry, and rendered by the reference beside
this document, which this links rather than restating: fifty-eight
declarations copied here would drift, and the store adds no drift of its
own because it copies field names verbatim. And the
correspondence to OpenTelemetry's GenAI conventions is a mapping
between two vocabularies rather than a property of one column, so it is
written out below where an exporter author reads it once.

Read-only, and deliberately so: nothing here opens a database, reads a
configuration file or needs a key.
"""

import textwrap

from sqlalchemy import Table

from vinga_server.conversations.schema import TABLES

# Where the reference wraps its prose. The tables cannot wrap (a row is
# a line), so only paragraphs go through this.
PROSE_WIDTH = 78

# The event vocabulary's authority, which sits beside this document in
# the same directory and is generated from the registry that declares
# every event.
EVENT_REFERENCE = "events.md"

# The domain model, one directory up from the committed reference. The
# schema is named `conversations` and stores sessions and turns, while
# the domain noun "conversation" is a thread that does not exist yet, so
# the reference names the page that holds the distinction. Relative to
# `docs/reference/`, where the reference is committed.
CONCEPTS = "../concepts.md"

# What an exporter maps onto, per the observability ADR's adoption of
# the GenAI conventions "where one exists". Left-hand side is this
# project's field name, right-hand side is the OTel attribute; the third
# column says where the field is found.
GEN_AI: tuple[tuple[str, str, str], ...] = (
    ("input_tokens", "gen_ai.usage.input_tokens", "`turns`, `turns.legs`, the `llm_round` event"),
    (
        "output_tokens",
        "gen_ai.usage.output_tokens",
        "`turns`, `turns.legs`, the `llm_round` event",
    ),
    ("model", "gen_ai.request.model", "the `llm_round`, `llm_retry` and `provider_failed` events"),
    ("type", "gen_ai.provider.name", "the provider-bearing events, and `sessions.providers`"),
    ("host", "server.address", "the provider-bearing events"),
)


def reference() -> str:
    """The whole reference document, rendered from the metadata."""
    lines = [
        "# Conversation store schema reference",
        "",
        "Generated from the SQLAlchemy metadata by `vinga-server conversations",
        "schema`. Do not edit this file by hand: CI regenerates it and fails on any",
        "difference, so an edit here is reverted by the next run. The text of a",
        "column description lives on the table in",
        "`vinga-server/vinga_server/conversations/schema.py`.",
        "",
        *_paragraph(
            "The store is the `conversations` schema of the Postgres database the "
            "`VINGA_DB_*` variables name, beside the domain configuration's `domain` "
            "schema. It holds what was said and what it cost to say it: the session "
            "spine, the turn timeline, the tool invocations a turn issued, and the "
            "decision track underneath them. Audio never enters it. The per-frame "
            "endpointer track and the dropped-frame counts stay in the session "
            "capture, which is the recording; this is the queryable record."
        ),
        "",
        *_paragraph(
            f"[The domain concepts page]({CONCEPTS}) says what a session and a "
            f"turn mean to a user, and holds the distinction this schema's name "
            f"invites: these are sessions and turns, not the cross-session "
            f"conversation the domain model plans."
        ),
        "",
        "## The compatibility promise",
        "",
        *_paragraph(
            "Table names, column names and event field names are a compatibility "
            "surface. They change only as breaking changes, announced in the "
            "changelog, the same promise the structured events carry. Columns are "
            "added additively and a row written before an addition reads it as null."
        ),
        "",
        "## What is stored, and what the two switches take away",
        "",
        *_paragraph(
            "Recording is off unless `server.conversations.enabled` says otherwise. "
            "Under it, two independent storage switches decide what a row keeps, and "
            "every combination is a supported configuration."
        ),
        "",
        "| Switch | On | Off |",
        "| --- | --- | --- |",
        "| `metrics` | every measured number, and one `events` row per structured "
        "event | the numeric columns are null and no `events` rows are written |",
        "| `text` | conversation text, and tool names, arguments and results | those "
        "columns are null; the rows still land |",
        "",
        *_paragraph(
            "Three kinds of column survive both switches, and each for a reason worth "
            "stating. The session spine (`sessions.session`, its device and its "
            "timestamps) survives because retention and every read key on it, and a "
            "record that cannot be pruned cannot be kept. The structural "
            "halves of a turn (`t_ms`, `agent`, `language`, `tool_calls`) survive "
            "because they are neither a measured number nor conversation text. And "
            "`sessions.metrics` and `sessions.text` record which way the switches "
            "were set for that session, so a null column is distinguishable from a "
            "column that was never stored."
        ),
        "",
        *_paragraph(
            "The switches are deployment-wide. Until per-user controls exist, "
            "enabling text storage on a device a household shares stores what guests "
            "say to it, which is the same statement the capture documentation makes "
            "about audio. Attributing a session on a shared device to one member "
            "needs voiceprint identification, which does not exist here yet, so the "
            "session is the unit deletion is expressed in: it is what retention "
            "takes whole and what the erasure API will address. Erasing one named "
            "session on demand is not enforceable in this release at all, and the "
            "section below says what a deployment has instead."
        ),
        "",
        "## Retention and deletion",
        "",
        *_paragraph(
            "`server.conversations.retention_days` defaults to 90. Whole sessions "
            "whose `started_at` is older than the window are deleted, row and "
            "children together, when the server starts and at each session close. "
            "`retention_days: 0` keeps everything and is a deliberate choice rather "
            "than a default: a store without a policy retains forever."
        ),
        "",
        *_paragraph(
            "Deletion on demand is not something this release has a command for. "
            "`vinga-server conversations purge` was one and is gone (#282), because "
            "it reached the store's file directly and that is not a thing a command "
            "can do once the store is a database elsewhere; erasing a named session "
            "returns as an act of the API, with a CLI verb in front of it (#190). "
            "Until then the window above is the whole of the deletion policy, and a "
            "deployment that has to erase something now does it in SQL, as the "
            "server role: `delete from conversations.sessions where session = ...` "
            "and the same predicate against `turns`, `tool_invocations` and "
            "`events`, in one transaction, because a session's rows go together or "
            "the deletion leaves children pointing at nothing. Whichever way rows "
            "go, the deletion the "
            "window takes is of a session at a time, row and children together: a "
            "session that is still running when its row goes stops being recorded, "
            "because the writer finds the row gone at its next turn. Capture files "
            "are a separate instrument and are never touched by any of it; the "
            "session id is the correlation key for whoever needs to remove the "
            "matching triplet."
        ),
        "",
        *_paragraph(
            "What deletion means is worth stating exactly, because the database "
            "server decides it. A deleted row is invisible to every transaction "
            "that begins after the deletion commits, including the read-only "
            "`vinga_ro` role's. A repeatable-read transaction that was already in "
            "flight when it committed keeps seeing the row until that transaction "
            "ends, which is what multi-version concurrency is and not something "
            "this server can prevent: a query left open in a terminal is one such "
            "transaction. Reclaiming the space the row occupied is the database "
            "server's own storage maintenance (autovacuum), not a per-delete "
            "overwrite, so the interval between the delete and the reclamation is "
            "the instance's to tune rather than this server's to promise. And "
            "copies that have already left the database (a `pg_dump`, a filesystem "
            "snapshot, a replica) are the operator's to manage."
        ),
        "",
        "## Reading it",
        "",
        *_paragraph(
            "There is no analysis command. The store is SQL, and the way to read it "
            "is a live read-only session as `vinga_ro`, the role "
            "`deploy/postgres-init.sql` provisions: it has `SELECT` on every table "
            "in this schema, now and after the next migration, and no access at all "
            "to the domain schema where the stored secrets' ciphertexts live. There "
            "is nothing to copy and nothing to copy safely."
        ),
        "",
        "```bash",
        "psql \"postgresql://vinga_ro@127.0.0.1:5432/vinga\" \\",
        "  -c 'select * from conversations.turns order by id desc limit 20'",
        "```",
        "",
        *_paragraph(
            "The role carries a `statement_timeout` and an "
            "`idle_in_transaction_session_timeout`, which are not tidiness: a "
            "reader's locks hold off the schema changes a migration makes, so a "
            "session left open in a transaction is what would make the next boot's "
            "migration wait out its lock timeout and refuse."
        ),
        "",
        *_paragraph(
            "The ids on `sessions`, `turns` and `events` are `bigint` identity "
            "columns, and a sequence never hands out a value twice. That is what "
            "makes them usable as cursors: a client that has read up to id N may ask "
            "for what came after it and cannot be handed a different row under the "
            "same number, even after retention has deleted from the end."
        ),
        "",
        "## The event vocabulary",
        "",
        *_paragraph(
            f"`events.name` and `events.fields` carry the structured event surface, "
            f"whose definition is the [event schema reference]({EVENT_REFERENCE}): "
            f"which events exist, and which fields each one carries. It is not "
            f"restated here, because a second copy of fifty-eight declarations is a "
            f"second copy to drift. The store copies field names verbatim from the "
            f"payload, minus "
            f"`event`, `session` and `device`, which live on the row and on the "
            f"session."
        ),
        "",
        *_paragraph(
            "Some fields never arrive. The writer strips `text` from `heard`, "
            "`replied` and `agent_said`, and `tool` from `tool_call`, before the row "
            "lands, and does so whatever the storage switches say: the `events` table "
            "is metadata-only from its first row."
        ),
        "",
        *_paragraph(
            "The two halves of that strip are in different states, which is worth "
            "knowing before reading a row. The three text fields no longer reach the "
            "events at all, so stripping them is defense in depth on the way in: it "
            "is applied where a row is written and by no read, so it says what lands "
            "in a database this server wrote and nothing about one written before the "
            "narrowing. `tool` does still reach "
            "`tool_call`, on the one branch that names a tool this server authored "
            "itself (a builtin); the strip removes it from the row anyway, so every "
            "name a call carries lives on `tool_invocations` under the text switch "
            "rather than in two tables under two rules. A called tool's name is "
            "content for the same reason its result is, since it is usually a "
            "device's self-description or an MCP server's vocabulary rather than "
            "anything this server authored."
        ),
        "",
        "## The OpenTelemetry GenAI correspondence",
        "",
        *_paragraph(
            "Usage and provider identity use the GenAI semantic conventions adapted "
            "to this project's field style, so an exporter maps by reading one table "
            "rather than by guessing."
        ),
        "",
        "| This project | OpenTelemetry | Where |",
        "| --- | --- | --- |",
        *[f"| `{name}` | `{attribute}` | {where} |" for name, attribute, where in GEN_AI],
        "",
        *_paragraph(
            "`stage` and `provider` keep their own names deliberately. `provider` is "
            "the configured entry's name, a vinga concept with different semantics "
            "from OTel's vendor field, and the convention is adopted where one "
            "exists rather than imposed where one does not."
        ),
        "",
        *_paragraph(
            "A turn's `input_tokens` and `output_tokens` are totals across its "
            "rounds, and after a handover they blend agents that may run different "
            "models. `turns.legs` carries the per-leg counts, and the per-round, "
            "per-model truth is the `llm_round` events in the same database, one join "
            "away."
        ),
        "",
        "## Tables",
        "",
    ]

    for table in TABLES:
        lines += _table_section(table)

    return "\n".join(lines).rstrip("\n") + "\n"


def _table_section(table: Table) -> list[str]:
    lines = [
        f"### `{table.name}`",
        "",
        "| Column | Type | Null | Description |",
        "| --- | --- | --- | --- |",
    ]
    lines += [
        f"| `{column.name}` | `{column.type}` | {_null(column.nullable)} | "
        f"{_cell(column.comment)} |"
        for column in table.columns
    ]
    lines.append("")
    return lines


def _null(nullable: bool) -> str:
    return "yes" if nullable else "no"


def _cell(comment: str | None) -> str:
    """Text inside a table cell. A pipe ends a cell even inside a code
    span, so it is escaped; and an undescribed column is a defect this
    makes visible rather than an empty cell to skim past."""
    if not comment:
        return "**(undescribed)**"
    return " ".join(comment.split()).replace("|", "\\|")


def _paragraph(prose: str) -> list[str]:
    """One paragraph, wrapped. The committed reference is read as a file
    as often as it is rendered, and an unwrapped paragraph makes every
    edit to it a one-line diff of the whole thing.

    Never inside a word or across a hyphen, for the reason the domain
    reference gives: the default would break an identifier in half and a
    code span split over two lines renders with a space in it."""
    return textwrap.wrap(prose, width=PROSE_WIDTH, break_long_words=False, break_on_hyphens=False)


__all__ = ["GEN_AI", "reference"]
