"""Every command spelling in the tree, found once and classified once.

The #223 re-cut respells every word of the configuration grammar, and
the spellings are quoted far outside the module that owns them: in the
example fragments, in both READMEs, in the deploy examples, in the smoke
seeds, in the event catalog's message templates, and in several hundred
lines of prose that are a record of what was true when they were
written. A sweep that misses one leaves a document telling a reader to
type a command this server does not have.

So the sweep is a tool rather than a grep, checked in and run twice.
Before the rename it emits the manifest beside it
(`command-spellings.txt`), one line per match with the class it was
given, which is what makes the sweep reviewable: a reader can see what
will move and what will deliberately stay stale, rather than being
asked to trust that the difference was thought about. After the rename
the same code is the standing guard: every match classified `respell`
has to name a command the registered tree actually has, so a stale
spelling fails a test rather than a review.

Regenerating the manifest is `uv run python -m tests.unit.test_command_spellings`
from `vinga-server/`, and the drift test below fails when the committed
copy and a fresh scan disagree.

Three classes, with the rule each is assigned by:

- **`respell`**, an invocation a reader is meant to run today. It moves
  to the new grammar, and the guard holds it to naming a registered
  command.
- **`historical`**, a record of what was true when it was written: the
  plans, the changelog, the feature notes, and the lines of the CLI
  guide that quote the merged grammar as a counterexample, an audit row
  or a recorded tension. Rewriting one would falsify the record.
- **`generated`**, output regenerated from the command tree, so
  respelling it by hand would be wrong twice: it would be reverted by
  the next render, and it would hide the render that should have
  happened.

Four invocation families are recognized, because the grammar is quoted
under four program words: `vinga-server config` (the checkout and
in-image spelling), `vinga config` (the docker shim the README's own
quick start defines), `vinga` (the console script this issue adds), and
the bare `config <verb>` shorthand prose uses inside backticks.
"""

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from tests.support.config_cli import registered
from vinga_server.config import cli

# The checkout, found from this file rather than from the working
# directory: the unit lane runs from `vinga-server/` and the sweep is
# over the whole repository.
REPO_ROOT = Path(__file__).resolve().parents[3]

MANIFEST = Path(__file__).with_name("command-spellings.txt")

# What the manifest says about itself, so a reader who opens it first
# knows what it is and what regenerates it.
MANIFEST_HEADER = (
    "# Every command spelling in the tree, classified. Generated by\n"
    "# tests/unit/test_command_spellings.py; do not edit by hand.\n"
    "#\n"
    "# One line per match: path:line  class  invocation\n"
)

# The words the old grammar's top level had, written out because they
# are the thing being retired: after the rename no registered row
# carries them, so nothing can derive them any more. A shorthand match
# is only recognized when the word after `config` is one of these or one
# the tree still has, which is what keeps `config file` and
# `config key` out of a sweep about commands.
_RETIRED_WORDS = frozenset(
    {
        "set",
        "delete",
        "bind-device",
        "add-device",
        "apply",
        "pending",
        "status",
        "prompt",
        "reload",
        "ota-url",
        "set-default-agent",
        "clear-default-agent",
        "set-secret",
        "clear-secret",
        "list",
        "schema",
        "reference",
        "openapi",
        "cli-reference",
        "show",
        "export",
    }
)


def _command_words() -> frozenset[str]:
    """Every word a recognized invocation may open with: the tree's own
    first words, and the ones the re-cut retired."""
    return _RETIRED_WORDS | {row.words[0] for row in cli.COMMANDS}


# One invocation, as a program word and the rest of its line. The
# alternation is longest first, so `vinga-server config` is read as
# itself rather than as the short spelling with a word after it, and
# the lookahead after the bare `vinga` is what keeps it from matching
# inside `vinga-server`.
#
# The rest of the line stops at the characters that end a command line
# in prose or in a shell: a closing backtick, a pipe, a redirect, a
# comment, a separator. What is captured is what a reader would type.
_TERMINATORS = "`;|&<>#\n"

_INVOCATION = re.compile(
    r"(?<![\w./-])(vinga-server config|vinga config|vinga)(?![\w-])"
    rf"[ \t]+([^{re.escape(_TERMINATORS)}]*)"
)

# The fourth family: `config <verb>` with no program word in front of
# it, which is how most prose refers to a command. Matched separately
# because it is the same shape with the prefix removed, and the spans
# the family above claimed are skipped so one line is not counted twice.
_SHORTHAND = re.compile(
    rf"(?<![\w./`-])(config)(?![\w-])[ \t]+([^{re.escape(_TERMINATORS)}]*)"
)

# Regenerated from the command tree, so a hand edit here is reverted by
# the next render and hides the render that should have happened.
_GENERATED_PATHS = (
    "docs/reference/cli.md",
    "docs/reference/events.md",
    "docs/reference/domain-config.md",
    "docs/reference/api-openapi.json",
)

# And the generated half of a spike, which is a captured experiment
# rather than a live artifact: neither respelled nor regenerated. Any
# directory named `generated` under a spike, so a second experiment
# inherits the rule rather than needing an entry.
_GENERATED_DIRECTORY = "/generated/"

# A record of what was true when it was written. The spikes' prose is
# here for the same reason their output is above: it reports an
# experiment run on a day, and rewriting it would falsify the report.
_HISTORICAL_PATHS = (
    "docs/plans/",
    "docs/features/",
    "docs/adr/",
    "spikes/",
    "CHANGELOG.md",
)

# The CLI guide is the one page that is both. It states the standard in
# the short spelling and quotes the merged grammar in the long one, as
# counterexamples, audit rows and recorded tensions; the quotes are the
# record and the standard is live. So the page is classified by the
# program word rather than by its path, and this is the rule:
_GUIDE = "docs/architecture/cli-guide.md"

# And its exceptions, which are shapes the page writes in the short
# spelling because the point is the grammar, and which no tree will
# ever answer to: a constructed counterexample is written to be
# rejected. Each is held to still appearing in the page, so an entry
# cannot go stale unnoticed.
_GUIDE_REJECTED = {
    # The address demoted to options, under "Identity addressing".
    "vinga set": "the constructed counterexample of an address written as flags",
}


@dataclass(frozen=True)
class Spelling:
    """One quoted invocation, where it is and what it is."""

    path: str
    line: int
    invocation: str
    kind: str

    def rendered(self) -> str:
        return f"{self.path}:{self.line}  {self.kind}  {self.invocation}"


def tracked() -> list[str]:
    """Every file git tracks, so an untracked scratch file cannot change
    the answer."""
    listed = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        check=True,
        text=True,
    )
    return sorted(name for name in listed.stdout.split("\0") if name)


def _text(path: str) -> str | None:
    """One tracked file's text, or None for one that is not text at all.

    A binary file has no command spelling in it, and a decoding failure
    here is a fact about the file rather than about the sweep.
    """
    try:
        return (REPO_ROOT / path).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return None


def _classified(path: str, program: str, invocation: str) -> str:
    """Which of the three classes one match belongs to.

    Path first, because a generated artifact is generated whatever it
    quotes and a record is a record whatever it quotes. The guide is
    the one page classified by its program word, for the reason stated
    above it.
    """
    if path.startswith(_GENERATED_PATHS) or _GENERATED_DIRECTORY in f"/{path}":
        return "generated"
    if path.startswith(_HISTORICAL_PATHS):
        return "historical"
    if path == _GUIDE:
        if invocation in _GUIDE_REJECTED or program != "vinga":
            return "historical"
        return "respell"
    return "respell"


def _command_line(program: str, rest: str, words: frozenset[str]) -> str | None:
    """One match as the invocation it quotes: the program word and the
    command words after it, and nothing else.

    The words stop at the first token that is not a bare command word,
    which is where an address, an option or the rest of a sentence
    begins. What is left is comparable between two sites that quote the
    same command with different arguments, which is what makes the
    manifest readable and the guard's job the tree's.
    """
    typed = rest.split()
    if not typed or typed[0] not in words:
        return None
    taken: list[str] = []
    for word in typed:
        if not _bare(word):
            break
        taken.append(word)
    return " ".join([program, *taken])


def _bare(word: str) -> bool:
    """Whether a token is a bare command word: letters, digits and
    dashes, opening with a letter. An address, an option, a path and a
    placeholder are each something else."""
    return bool(word) and word[0].isalpha() and word.replace("-", "").isalnum()


def _matches(path: str, text: str, words: frozenset[str]) -> list[Spelling]:
    """Every recognized invocation in one file."""
    found: list[Spelling] = []
    for number, line in enumerate(text.splitlines(), start=1):
        claimed: list[tuple[int, int]] = []
        for match in _INVOCATION.finditer(line):
            quoted = _command_line(match.group(1), match.group(2).strip(), words)
            if quoted is None:
                continue
            claimed.append(match.span())
            found.append(
                Spelling(
                    path=path,
                    line=number,
                    invocation=quoted,
                    kind=_classified(path, match.group(1), quoted),
                )
            )
        for match in _SHORTHAND.finditer(line):
            if any(start <= match.start() < end for start, end in claimed):
                continue
            quoted = _command_line("config", match.group(2).strip(), words)
            if quoted is None:
                continue
            found.append(
                Spelling(
                    path=path,
                    line=number,
                    invocation=quoted,
                    kind=_classified(path, "config", quoted),
                )
            )
    return found


def census() -> list[Spelling]:
    """Every command spelling in the tree, in file and line order."""
    words = _command_words()
    found: list[Spelling] = []
    for path in tracked():
        if path == str(MANIFEST.relative_to(REPO_ROOT)):
            continue
        text = _text(path)
        if text is None:
            continue
        found += _matches(path, text, words)
    return found


def manifest() -> str:
    """The census as the committed manifest reads."""
    return MANIFEST_HEADER + "".join(f"{row.rendered()}\n" for row in census())


# The guard
#
# A `respell` match is an invocation a reader is meant to run, so its
# words have to name something the tree has. Which row a command line
# names is `tests.support.config_cli.registered`, the one matcher the
# live lane and the wheel lane read too; what this adds is the other
# thing prose legitimately quotes, which is a group word with no verb
# after it (`the vinga-server config set-secret commands`). A group is
# a node of the same tree, so it is read off the same table.


def _nodes() -> frozenset[tuple[str, ...]]:
    """Every path the registered tree answers to: each row, and each
    group on the way to one."""
    return frozenset(
        row.words[:length]
        for row in cli.COMMANDS
        for length in range(1, len(row.words) + 1)
    )


def _typed(invocation: str) -> tuple[str, ...]:
    """The command words of one invocation: what follows the program
    word."""
    rest = invocation.split()
    for prefix in (("vinga-server", "config"), ("vinga", "config"), ("vinga",), ("config",)):
        if tuple(rest[: len(prefix)]) == prefix:
            return tuple(rest[len(prefix) :])
    return tuple(rest)


def names_something(invocation: str) -> bool:
    """Whether one quoted invocation names a command or a group the
    tree actually has."""
    typed = _typed(invocation)
    if registered(typed) is not None:
        return True
    nodes = _nodes()
    return any(typed[:length] in nodes for length in range(len(typed), 0, -1))


def test_the_manifest_is_the_census() -> None:
    """The committed classification, held to a fresh scan.

    The manifest is the reviewable half of this sweep, so it is checked
    the way every other generated artifact in this repository is: it is
    rendered again and diffed, and a change to what the tree quotes
    fails here until the manifest is regenerated with it.
    """
    assert MANIFEST.read_text(encoding="utf-8") == manifest()


def test_every_live_spelling_names_a_command_the_tree_has() -> None:
    """The standing guard.

    A `respell` match is an invocation somebody is meant to type. If its
    words do not name a row of the registration table, the document
    naming it is telling a reader to run a command this server does not
    have, which is the failure the whole sweep exists to prevent.
    """
    stale = [
        row.rendered()
        for row in census()
        if row.kind == "respell" and not names_something(row.invocation)
    ]
    assert stale == []


def test_the_guides_rejected_shapes_still_appear() -> None:
    """The guide's exemptions, held to being about something.

    An entry naming a shape the page has since stopped writing would
    quietly widen what a `respell` match is allowed to be.
    """
    quoted = {row.invocation for row in census() if row.path == _GUIDE}
    assert sorted(_GUIDE_REJECTED) == sorted(set(_GUIDE_REJECTED) & quoted)


def test_every_class_is_one_of_the_three() -> None:
    """The vocabulary, kept closed. A fourth class would be a
    classification nobody stated a rule for."""
    assert {row.kind for row in census()} <= {"respell", "historical", "generated"}


if __name__ == "__main__":  # pragma: no cover - the regeneration entry point
    MANIFEST.write_text(manifest(), encoding="utf-8")
    sys.stdout.write(f"wrote {MANIFEST}\n")
